server {
    listen 80;
    listen [::]:80;

    server_name www.neuradix.com;

    root /var/www/neuradix_website/site;
    index index.html;

    access_log /var/log/nginx/neuradix.access.log;
    error_log  /var/log/nginx/neuradix.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }

    location = /robots.txt { access_log off; log_not_found off; }
    location = /favicon.ico { access_log off; log_not_found off; }
}
