server {
    listen 80;
    listen [::]:80;
    server_name www.neuradix.com;

    location /.well-known/acme-challenge/ {
        root /var/www/neuradix_website/site;
    }

    location / {
        return 301 https://www.neuradix.com$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name www.neuradix.com;

    root /var/www/neuradix_website/site;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/www.neuradix.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/www.neuradix.com/privkey.pem;

    access_log /var/log/nginx/neuradix.access.log;
    error_log  /var/log/nginx/neuradix.error.log;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }

    location = /robots.txt { access_log off; log_not_found off; }
    location = /favicon.ico { access_log off; log_not_found off; }
}
